name: ezstore
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  html: ^0.15.5
  fluttertoast: ^8.2.8
  intl_phone_number_input: ^0.7.5
  pinput: ^5.0.2

  persistent_bottom_nav_bar_v2: ^6.1.0

  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  rename: ^3.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/category/
    - assets/product/
    - assets/my_orders/
    - assets/profile_menu/




flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21